repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - pandas-stubs
  - repo: local
    hooks:
      - id: merge-conflict-check
        name: Check for merge conflicts
        entry: bash -c 'rg --files-with-matches "^(<<<<<<<|=======|>>>>>>>)" && exit 1 || exit 0'
        language: system
        pass_filenames: false
