name: agent-cron
on:
  schedule:
    - cron: "30 22 * * *"   # 08:30 Melbourne time (AEST/AEDT handled by you changing if needed)
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agent
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Write service account key
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service_account.json
      - name: Renewals 30 days
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: service_account.json
          GOOGLE_SUBJECT_EMAIL: ${{ secrets.GOOGLE_SUBJECT_EMAIL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_SUCCESS_URL: ${{ secrets.STRIPE_SUCCESS_URL }}
          STRIPE_CANCEL_URL: ${{ secrets.STRIPE_CANCEL_URL }}
          SMS_PROVIDER: ${{ secrets.SMS_PROVIDER }}
          CLICKSEND_USER: ${{ secrets.CLICKSEND_USER }}
          CLICKSEND_KEY: ${{ secrets.CLICKSEND_KEY }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
        run: python -m agent.cli renewals 30
      - name: Renewals 7 days
        run: python -m agent.cli renewals 7
      - name: Renewals 0 days
        run: python -m agent.cli renewals 0
