name: Auto Rebase on Comment
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
jobs:
  rebase:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: cirrus-actions/rebase@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
