name: CI
on:
  push:
    branches: ["**"]
  pull_request:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      # Bootstrap mode: pass even if legacy code isn't lint-clean yet.
      # After the repo stabilizes, remove --exit-zero to enforce.
      - name: Lint and format (ruff)
        run: |
          pip show ruff >/dev/null 2>&1 || pip install ruff
          ruff check . --fix --exit-zero
          ruff format .

      - name: Type check (mypy) — soft gate initially
        run: |
          pip show mypy >/dev/null 2>&1 || pip install mypy
          mypy . || true

      - name: Tests — soft gate initially
        run: |
          pip show pytest >/dev/null 2>&1 || pip install pytest
          pip show pytest-xdist >/dev/null 2>&1 || pip install pytest-xdist
          pytest -n auto --maxfail=1 || true
