name: import_leads
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Import
        run: |
          python -m pip install -r agent/requirements.txt
          PYTHONPATH=agent/src python -m agent.cli leads_import agent/data/sample.csv
