name: PR Sanity
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure branch is up to date with main
        run: |
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD || {
            echo "Branch is not up to date with origin/main"
            exit 1
          }
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
