name: scrape_agencies
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scrape
        run: |
          python -m pip install -r agent/requirements.txt
          PYTHONPATH=agent/src python -m agent.cli leads_enrich agent/data/sample.csv
