name: stripe_sync

on:
  schedule:
    - cron: '30 20 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -e ./agent
      - name: Reconcile payments
        run: python -m agent.cli stripe_sync
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
