name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: agent/requirements.txt
      - name: Install dependencies
        run: |
          pip install -r agent/requirements.txt
          pip install ruff mypy pytest pytest-cov
      - name: Lint
        run: ruff check agent/src
      - name: Type check
        run: mypy agent/src
      - name: Run tests
        run: |
          PYTHONPATH=agent/src pytest --maxfail=1 --disable-warnings -q --cov=agent --cov-report=term-missing
